---
title: "QCA3"
author: "Akira Sasaki"
date: "01/03/2017"
output: word_document
---

```{r}

rm(list = ls()) #remove all lists in the right window
#for () loops
m <- matrix(1:5, nrow = 2, ncol = 5)
for(j in 1:3){
  m[,j]=0
} #change from 1st to 3rd columns into 0

for(j in 3:5){
  m[,j]=0
}

m1 <- matrix(1:10, nrow = 2, ncol = 5)
m1
for(i in 1:5) {
  m1[2, i] <- 0
}
```

```{r}
m2 <- matrix(1:6, nrow = 3)
m2

for (i in 1:3) {
    m2[i, 1] <- NA
  }
```

#Task 4

```{r}
m3 <- matrix(1:20, nrow = 4, ncol = 5)
m4 <- matrix(NA, nrow = 4, ncol = 5)

counter = 1
for (i in 1:4) {
  for(j in 1:5) {
    m4[i, j] = counter
    counter = counter + 1
  }
} #adapt m4 to m3

for (i in 1:4) {
  for(j in 1:5) {
    m4[i, j] = m3[i, j]
  }
} #replace observations in m4 with those in m3
```

#if()
```{r}
a <- 4
b <- 3
number <- 0
if(a<b){
  number = number + 1
}
number
# if a is smaller than b, show number + 1
```

#Creating Functions
```{r}
fun_mean <- function(x){
  sum(x)/length(x)
}

data(swiss)
fun_mean(x =swiss$Infant.Mortality)

add_two <- function(x){
  x + 2
}
add_two(10) #add 2 to 10

square <- function(x){
  x*x
}
square(2)
square(c(2, 3))

times_two <- function(x){
  x * 2
}
times_two(swiss$Catholic)

double <- function(x){
  output <- x * 2
  output
}
double(8)
```

#Apply function
```{r}
m <- matrix(c(1:10, 11:20), nrow = 10, ncol = 2)
#mean of the rows
m
apply(m, 1, mean) #1 indicates rows, 2 indicates colums

m <- matrix(1:100, nrow = 10, ncol = 2)
apply(m, 1, mean) # the same with the above

apply(swiss[, c("Catholic", "Infant.Mortality")], 1, mean)
apply(swiss[, 5:6], 2, mean)

```

#plotting
```{r}
#histogram
data(swiss)
hist(swiss$Infant.Mortality, feq = FALSE, main = "Fertility Rates")

#dotchart
dotchart(swiss[1:5, 2], labels = rownames(swiss))
dotchart(swiss$Eudcation, labels = rownames(swiss))

#ggplot2
library(ggplot2)
ggplot(data = swiss) + geom_point(mapping = aes(x = swiss$Infant.Mortality, y =swiss$Eudcation))

```

